### ISSUE TITLE
Prettier Empty Provider on Map

### ISSUE THREAD

**Issue by DeveloperKhan** [GTBitsOfGood/MapScout#183]
### Difficulty
Easy (1 person)

### Description
Add a small message to indicate 0 search results on the map. Ask Adib for the sad map image.

Current look:
<img width="1031" alt="Screen Shot 2021-09-14 at 2 28 45 PM" src="https://user-images.githubusercontent.com/26877561/133313474-ac756ad4-abf3-4192-9125-dd713b670e14.png">

Preferred look:
<img width="685" alt="Screen Shot 2021-09-14 at 2 28 35 PM" src="https://user-images.githubusercontent.com/26877561/133313530-0df1f7a8-1db8-45eb-8069-2c19d7ba214f.png">

**Comment by hdemusg** [comment]
Since this was already merged, I'll go ahead and close this issue.
