### ISSUE TITLE
[Ticket] [PMT] [Investigation] Investigate Waitlist Issues

### ISSUE THREAD

**Issue by jaynagpaul** [GTBitsOfGood/MapScout#224]
### Nonprofit Description
Mapscout is intended for nonprofits who need a customizable and intuitive method to display location based data in a map format (think Yelp or Airbnb for nonprofits). As a custom solution turned general solution, Mapscout is striving to expand features that our existing clients want or will want. In addition, we are focusing on simplifying the presentation of our product in order to bring in new users to our ecosystem.

### Ticket Description

This ticket is an **investigation ticket.** 

Mapscout has a waitlist functionality that sends new requests and links to a slack channel in BoG. Recently, the waitlist form for Mapscout has stopped sending new notifications. We would like to figure out why this functionality has stopped working so we may fix it in a future sprint.

### Acceptance Criteria
- [ ] We have the necessary information to fix the issue in a future sprint
- [ ] **BONUS:** The issue is fixed, and the waitlist sends Slack notifications as expected (if you have extra time)

### Other Notes

- Reach out to leadership for project secrets
- Follow the README for setup and ask for questions if you run into issues!

**Comment by vidushiMaheshwari** [comment]
1. Going through the history of commits on production(master) branch I couldn't find when the feature existed (or atleast it was not in the codebase).
2. Following the first point, I think that a this functionality can be created through CEL on firbase and slack integration. [(Link1)](https://cloud.google.com/build/docs/configuring-notifications/configure-slack) [(Link2)](https://skcript.com/svr/send-slack-notifications-using-firebase-cloud-functions-fireStore/)
3. Currently, in the dev branch, if you click on "signing up" for waitlist there is just a popup which was probably created to be used as form however it is just a blocker currently. If we only require user's email we might not need the form, however the signing process as far as i understood also looks at user's organization so maybe a popup be useful.
4. The dev branch is setting the user's info in firestore's corresponding waitlist doc so thats not something we have to work on.
