### ISSUE TITLE
[PMT] Template Refresh Deletes

### ISSUE THREAD

**Issue by colin4554** [GTBitsOfGood/MapScout#257]
Determine if there is a bug with the template creation logic. If there is not, simply remove the text telling the user to refresh the page. Start with examing the function on line 216 of the [template component](https://github.com/GTBitsOfGood/MapScout/blob/develop/src/components/template/index.tsx)

View [Notion for more information](https://www.notion.so/gtbitsofgood/Template-Refresh-Deletes-78b3e719e5da4f55b700eb2f1a1f95e5)

**Comment by cynthiazhang755** [comment]
I can't test cuz there's the API key issue :(
