### ISSUE TITLE
[PMT] Remove Toggle Feature and Filter

### ISSUE THREAD

**Issue by avayedawadi** [GTBitsOfGood/MapScout#259]
The toggle feature and filter currently doesn't serve a purpose and just has filler text instead of anything of value.

Go in and comment this feature out. Don't get rid of it entirely in case we would like to re-implement it at some point. Make a comment about the functionality of the toggle for the next developer who comes along.

![image](https://github.com/GTBitsOfGood/MapScout/assets/45608655/d012e259-ac27-436d-8548-1b023829424b)

![image](https://github.com/GTBitsOfGood/MapScout/assets/45608655/1866f4b5-01d3-4757-8f4c-33a0d98125f6)

**Comment by cynthiazhang755** [comment]
I can't test cuz of API key :(
