### ISSUE TITLE
Typescript issues

### ISSUE THREAD

**Issue by thanasis457** [GTBitsOfGood/MapScout#278]
### Description

Fix the Sentry and ConnectedRouter errors that are due to type errors

**Comment by nickspaargaren** [comment]
@thanasis457, I don't think these errors are fixed yet. That's why i recently opened https://github.com/GTBitsOfGood/MapScout/pull/281. You might want to take a look at this PR.

**Comment by thanasis457** [comment]
@nickspaargaren Thank you so much for your PR! I seriously appreciate your help. We are a student org helping out non-profits and any help is much appreciated.

I did run the project and indeed new errors have started popping up. This is a pretty old project and a lot of the issues will only be resolved by a massive upgrade of the packages. For now, I have identified the few packages that were causing the issues and will change the package.json file to limit upgrades to patches (no minor updates since those were introducing TS issues).

There are a lot more features to be implemented so upgrading packages is not really a priority now.

**Comment by nickspaargaren** [comment]
You are welcome @thanasis457! Sounds like a helpful project!
I've already did some major dependency upgrades last week for you to resolve the newly introduced errors. Check it out and let me know if i need to explain anything else. Happy to help!
