### ISSUE TITLE
Chart Components - Linegraph, Progress Bar, Pie chart

### ISSUE THREAD

**Issue by thanasis457** [GTBitsOfGood/MapScout#279]
### Description

Create React components for a Linegraph, Progress Bar, and Pie chart as shown in the Figma:

![Image](https://github.com/user-attachments/assets/ef2b00a5-cb56-4b3a-bbfe-f4ba000153a3)

The "Donate now" buttons should redirect to a link passed in by the user.

Ensure that the components behave correctly while resizing.
Please make use of vanilla [D3](https://github.com/d3/d3) and avoid making use of 3rd party component libraries.
You should only create the component within the collapsible boxes. i.e. the component you will create should not be collapsible or have any frame around them.

- [ ] Line Graph
- [ ] Proggress Bar
- [ ] Pie Chart

**Comment by charliejlin** [comment]
I just added the components to the modal when you click on any provider from the map view. I left my testing components and their info in "map/index", if you wanted to see for yourself, but lmk and I can just remove the test data and the components.
